---
name: 🛠️ Feature Request
description: Suggest an idea to help us improve our product
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request report!**
        We kindly ask that you search to see if an issue [already exists](https://github.com/orgs/Karaka-Management/projects/10) for your feature.
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: |
        Describe the solution you'd like. A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Describe alternatives you've considered.
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to follow our [CoC](https://jingga.app/en/coc), [Terms](https://jingga.app/en/terms) and [CLA](https://jingga.app/en/cla)
      options:
        - label: I agree to follow this project's Code of Conduct (CoC), Terms and Contributor License Agreement (CLA)
          required: true
